/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * A result representing a single torrent on EZTV
 */
@ApiModel(description = "A result representing a single torrent on EZTV")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-03-13T22:46:52.366520-06:00[America/Chicago]")
public class EztvResult {
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_HASH = "hash";
    public static final String SERIALIZED_NAME_FILENAME = "filename";
    public static final String SERIALIZED_NAME_EPISODE_URL = "episode_url";
    public static final String SERIALIZED_NAME_TORRENT_URL = "torrent_url";
    public static final String SERIALIZED_NAME_MAGNET_URL = "magnet_url";
    public static final String SERIALIZED_NAME_TITLE = "title";
    public static final String SERIALIZED_NAME_IMDB_ID = "imdb_id";
    public static final String SERIALIZED_NAME_SEASON = "season";
    public static final String SERIALIZED_NAME_EPISODE = "episode";
    public static final String SERIALIZED_NAME_SMALL_SCREENSHOT =
            "small_screenshot";
    public static final String SERIALIZED_NAME_LARGE_SCREENSHOT =
            "large_screenshot";
    public static final String SERIALIZED_NAME_SEEDS = "seeds";
    public static final String SERIALIZED_NAME_PEERS = "peers";
    public static final String SERIALIZED_NAME_DATE_RELEASED_UNIX =
            "date_released_unix";
    public static final String SERIALIZED_NAME_SIZE_BYTES = "size_bytes";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    @SerializedName(SERIALIZED_NAME_HASH)
    private String hash;
    @SerializedName(SERIALIZED_NAME_FILENAME)
    private String filename;
    @SerializedName(SERIALIZED_NAME_EPISODE_URL)
    private String episodeUrl;
    @SerializedName(SERIALIZED_NAME_TORRENT_URL)
    private String torrentUrl;
    @SerializedName(SERIALIZED_NAME_MAGNET_URL)
    private String magnetUrl;
    @SerializedName(SERIALIZED_NAME_TITLE)
    private String title;
    @SerializedName(SERIALIZED_NAME_IMDB_ID)
    private String imdbId;
    @SerializedName(SERIALIZED_NAME_SEASON)
    private String season;
    @SerializedName(SERIALIZED_NAME_EPISODE)
    private String episode;
    @SerializedName(SERIALIZED_NAME_SMALL_SCREENSHOT)
    private String smallScreenshot;
    @SerializedName(SERIALIZED_NAME_LARGE_SCREENSHOT)
    private String largeScreenshot;
    @SerializedName(SERIALIZED_NAME_SEEDS)
    private Integer seeds;
    @SerializedName(SERIALIZED_NAME_PEERS)
    private Integer peers;
    @SerializedName(SERIALIZED_NAME_DATE_RELEASED_UNIX)
    private String dateReleasedUnix;
    @SerializedName(SERIALIZED_NAME_SIZE_BYTES)
    private String sizeBytes;

    public EztvResult id(Integer id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public EztvResult hash(String hash) {

        this.hash = hash;
        return this;
    }

    /**
     * Get hash
     *
     * @return hash
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public EztvResult filename(String filename) {

        this.filename = filename;
        return this;
    }

    /**
     * Get filename
     *
     * @return filename
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public EztvResult episodeUrl(String episodeUrl) {

        this.episodeUrl = episodeUrl;
        return this;
    }

    /**
     * Get episodeUrl
     *
     * @return episodeUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getEpisodeUrl() {
        return episodeUrl;
    }

    public void setEpisodeUrl(String episodeUrl) {
        this.episodeUrl = episodeUrl;
    }

    public EztvResult torrentUrl(String torrentUrl) {

        this.torrentUrl = torrentUrl;
        return this;
    }

    /**
     * Get torrentUrl
     *
     * @return torrentUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTorrentUrl() {
        return torrentUrl;
    }

    public void setTorrentUrl(String torrentUrl) {
        this.torrentUrl = torrentUrl;
    }

    public EztvResult magnetUrl(String magnetUrl) {

        this.magnetUrl = magnetUrl;
        return this;
    }

    /**
     * Get magnetUrl
     *
     * @return magnetUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMagnetUrl() {
        return magnetUrl;
    }

    public void setMagnetUrl(String magnetUrl) {
        this.magnetUrl = magnetUrl;
    }

    public EztvResult title(String title) {

        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public EztvResult imdbId(String imdbId) {

        this.imdbId = imdbId;
        return this;
    }

    /**
     * Get imdbId
     *
     * @return imdbId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getImdbId() {
        return imdbId;
    }

    public void setImdbId(String imdbId) {
        this.imdbId = imdbId;
    }

    public EztvResult season(String season) {

        this.season = season;
        return this;
    }

    /**
     * Get season
     *
     * @return season
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSeason() {
        return season;
    }

    public void setSeason(String season) {
        this.season = season;
    }

    public EztvResult episode(String episode) {

        this.episode = episode;
        return this;
    }

    /**
     * Get episode
     *
     * @return episode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getEpisode() {
        return episode;
    }

    public void setEpisode(String episode) {
        this.episode = episode;
    }

    public EztvResult smallScreenshot(String smallScreenshot) {

        this.smallScreenshot = smallScreenshot;
        return this;
    }

    /**
     * Get smallScreenshot
     *
     * @return smallScreenshot
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSmallScreenshot() {
        return smallScreenshot;
    }

    public void setSmallScreenshot(String smallScreenshot) {
        this.smallScreenshot = smallScreenshot;
    }

    public EztvResult largeScreenshot(String largeScreenshot) {

        this.largeScreenshot = largeScreenshot;
        return this;
    }

    /**
     * Get largeScreenshot
     *
     * @return largeScreenshot
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLargeScreenshot() {
        return largeScreenshot;
    }

    public void setLargeScreenshot(String largeScreenshot) {
        this.largeScreenshot = largeScreenshot;
    }

    public EztvResult seeds(Integer seeds) {

        this.seeds = seeds;
        return this;
    }

    /**
     * Get seeds
     *
     * @return seeds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getSeeds() {
        return seeds;
    }

    public void setSeeds(Integer seeds) {
        this.seeds = seeds;
    }

    public EztvResult peers(Integer peers) {

        this.peers = peers;
        return this;
    }

    /**
     * Get peers
     *
     * @return peers
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPeers() {
        return peers;
    }

    public void setPeers(Integer peers) {
        this.peers = peers;
    }

    public EztvResult dateReleasedUnix(String dateReleasedUnix) {

        this.dateReleasedUnix = dateReleasedUnix;
        return this;
    }

    /**
     * Get dateReleasedUnix
     *
     * @return dateReleasedUnix
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDateReleasedUnix() {
        return dateReleasedUnix;
    }

    public void setDateReleasedUnix(String dateReleasedUnix) {
        this.dateReleasedUnix = dateReleasedUnix;
    }

    public EztvResult sizeBytes(String sizeBytes) {

        this.sizeBytes = sizeBytes;
        return this;
    }

    /**
     * Get sizeBytes
     *
     * @return sizeBytes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSizeBytes() {
        return sizeBytes;
    }

    public void setSizeBytes(String sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EztvResult eztvResult = (EztvResult) o;
        return Objects.equals(this.id, eztvResult.id) &&
                Objects.equals(this.hash, eztvResult.hash) &&
                Objects.equals(this.filename, eztvResult.filename) &&
                Objects.equals(this.episodeUrl, eztvResult.episodeUrl) &&
                Objects.equals(this.torrentUrl, eztvResult.torrentUrl) &&
                Objects.equals(this.magnetUrl, eztvResult.magnetUrl) &&
                Objects.equals(this.title, eztvResult.title) &&
                Objects.equals(this.imdbId, eztvResult.imdbId) &&
                Objects.equals(this.season, eztvResult.season) &&
                Objects.equals(this.episode, eztvResult.episode) &&
                Objects.equals(this.smallScreenshot, eztvResult.smallScreenshot) &&
                Objects.equals(this.largeScreenshot, eztvResult.largeScreenshot) &&
                Objects.equals(this.seeds, eztvResult.seeds) &&
                Objects.equals(this.peers, eztvResult.peers) &&
                Objects.equals(this.dateReleasedUnix, eztvResult.dateReleasedUnix) &&
                Objects.equals(this.sizeBytes, eztvResult.sizeBytes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, hash, filename, episodeUrl, torrentUrl, magnetUrl,
                title, imdbId, season, episode, smallScreenshot,
                largeScreenshot, seeds, peers, dateReleasedUnix,
                sizeBytes);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EztvResult {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
        sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
        sb.append("    episodeUrl: ")
                .append(toIndentedString(episodeUrl))
                .append("\n");
        sb.append("    torrentUrl: ")
                .append(toIndentedString(torrentUrl))
                .append("\n");
        sb.append("    magnetUrl: ")
                .append(toIndentedString(magnetUrl))
                .append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    imdbId: ").append(toIndentedString(imdbId)).append("\n");
        sb.append("    season: ").append(toIndentedString(season)).append("\n");
        sb.append("    episode: ").append(toIndentedString(episode)).append("\n");
        sb.append("    smallScreenshot: ")
                .append(toIndentedString(smallScreenshot))
                .append("\n");
        sb.append("    largeScreenshot: ")
                .append(toIndentedString(largeScreenshot))
                .append("\n");
        sb.append("    seeds: ").append(toIndentedString(seeds)).append("\n");
        sb.append("    peers: ").append(toIndentedString(peers)).append("\n");
        sb.append("    dateReleasedUnix: ")
                .append(toIndentedString(dateReleasedUnix))
                .append("\n");
        sb.append("    sizeBytes: ")
                .append(toIndentedString(sizeBytes))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
