/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * InlineObject1
 */
@SuppressWarnings("unused")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class InlineObject1 {
    public static final String SERIALIZED_NAME_MAGNET = "magnet";
    @SerializedName(SERIALIZED_NAME_MAGNET)
    private String magnet;

    @SuppressWarnings("unused")
    public InlineObject1 magnet(String magnet) {

        this.magnet = magnet;
        return this;
    }

    /**
     * Magnet link
     *
     * @return magnet
     **/
    @SuppressWarnings("unused")
    @ApiModelProperty(required = true, value = "Magnet link")

    public String getMagnet() {
        return magnet;
    }

    @SuppressWarnings("unused")
    public void setMagnet(String magnet) {
        this.magnet = magnet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineObject1 inlineObject1 = (InlineObject1) o;
        return Objects.equals(this.magnet, inlineObject1.magnet);
    }

    @Override
    public int hashCode() {
        return Objects.hash(magnet);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineObject1 {\n");
        sb.append("    magnet: ").append(toIndentedString(magnet)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
