/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Body of the login request
 */
@ApiModel(description = "Body of the login request")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-04-15T16:42:07.120298-05:00[America/Chicago]")
public class LoginBody {
    public static final String SERIALIZED_NAME_APIKEY = "apikey";
    public static final String SERIALIZED_NAME_PIN = "pin";
    @SerializedName(SERIALIZED_NAME_APIKEY)
    private String apikey;
    @SerializedName(SERIALIZED_NAME_PIN)
    private String pin;

    public LoginBody apikey(String apikey) {

        this.apikey = apikey;
        return this;
    }

    /**
     * TheTVDB API Key
     *
     * @return apikey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "TheTVDB API Key")

    public String getApikey() {
        return apikey;
    }

    public void setApikey(String apikey) {
        this.apikey = apikey;
    }

    public LoginBody pin(String pin) {

        this.pin = pin;
        return this;
    }

    /**
     * TheTVDB Subscriber Pin
     *
     * @return pin
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "TheTVDB Subscriber Pin")

    public String getPin() {
        return pin;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LoginBody loginBody = (LoginBody) o;
        return Objects.equals(this.apikey, loginBody.apikey) &&
                Objects.equals(this.pin, loginBody.pin);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apikey, pin);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LoginBody {\n");
        sb.append("    apikey: ").append(toIndentedString(apikey)).append("\n");
        sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
