/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Ratings for a movie from OMDB
 */
@SuppressWarnings("unused")
@ApiModel(description = "Ratings for a movie from OMDB")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class OmdbItemRating {
    public static final String SERIALIZED_NAME_SOURCE = "Source";
    public static final String SERIALIZED_NAME_VALUE = "Value";
    @SerializedName(SERIALIZED_NAME_SOURCE)
    private String source;
    @SerializedName(SERIALIZED_NAME_VALUE)
    private String value;

    public OmdbItemRating source(String source) {

        this.source = source;
        return this;
    }

    /**
     * Rating Source
     *
     * @return source
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Rating Source")

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public OmdbItemRating value(String value) {

        this.value = value;
        return this;
    }

    /**
     * Rating Value
     *
     * @return value
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Rating Value")

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OmdbItemRating omdbItemRating = (OmdbItemRating) o;
        return Objects.equals(this.source, omdbItemRating.source) &&
                Objects.equals(this.value, omdbItemRating.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(source, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OmdbItemRating {\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
