/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * Ratings for a movie from OMDb
 */
@SuppressWarnings("unused")
@Generated(value = "net.celestialdata.plexbot.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-23T04:57:45.670Z[GMT]")
public class OmdbMovieRating {
    @SerializedName("Source")
    private String source = null;

    @SerializedName("Value")
    private String value = null;

    @SuppressWarnings("unused")
    public OmdbMovieRating source(String source) {
        this.source = source;
        return this;
    }

    /**
     * Rating Source
     *
     * @return source
     **/
    @SuppressWarnings("unused")
    public String getSource() {
        return source;
    }

    @SuppressWarnings("unused")
    public void setSource(String source) {
        this.source = source;
    }

    @SuppressWarnings("unused")
    public OmdbMovieRating value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Rating Value
     *
     * @return value
     **/
    @SuppressWarnings("unused")
    public String getValue() {
        return value;
    }

    @SuppressWarnings("unused")
    public void setValue(String value) {
        this.value = value;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OmdbMovieRating omdbMovieRating = (OmdbMovieRating) o;
        return Objects.equals(this.source, omdbMovieRating.source) &&
                Objects.equals(this.value, omdbMovieRating.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(source, value);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OmdbMovieRating {\n");

        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
