/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.net.URI;
import java.util.Objects;

/**
 * PlexUserUser
 */
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class PlexUserUser {
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_UUID = "uuid";
    public static final String SERIALIZED_NAME_EMAIL = "email";
    public static final String SERIALIZED_NAME_JOINED_AT = "joined_at";
    public static final String SERIALIZED_NAME_USERNAME = "username";
    public static final String SERIALIZED_NAME_TITLE = "title";
    public static final String SERIALIZED_NAME_THUMB = "thumb";
    public static final String SERIALIZED_NAME_AUTH_TOKEN = "authToken";
    public static final String SERIALIZED_NAME_AUTHENTICATION_TOKEN =
            "authentication_token";
    public static final String SERIALIZED_NAME_SUBSCRIPTION = "subscription";
    public static final String SERIALIZED_NAME_ROLES = "roles";
    public static final String SERIALIZED_NAME_CONFIRMED_AT = "confirmedAt";
    public static final String SERIALIZED_NAME_REMEMBER_ME = "rememberMe";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    @SerializedName(SERIALIZED_NAME_UUID)
    private String uuid;
    @SerializedName(SERIALIZED_NAME_EMAIL)
    private String email;
    @SerializedName(SERIALIZED_NAME_JOINED_AT)
    private String joinedAt;
    @SerializedName(SERIALIZED_NAME_USERNAME)
    private String username;
    @SerializedName(SERIALIZED_NAME_TITLE)
    private String title;
    @SerializedName(SERIALIZED_NAME_THUMB)
    private URI thumb;
    @SerializedName(SERIALIZED_NAME_AUTH_TOKEN)
    private String authToken;
    @SerializedName(SERIALIZED_NAME_AUTHENTICATION_TOKEN)
    private String authenticationToken;
    @SerializedName(SERIALIZED_NAME_SUBSCRIPTION)
    private PlexUserUserSubscription subscription;
    @SerializedName(SERIALIZED_NAME_ROLES)
    private PlexUserUserRoles roles;
    @SerializedName(SERIALIZED_NAME_CONFIRMED_AT)
    private String confirmedAt;
    @SerializedName(SERIALIZED_NAME_REMEMBER_ME)
    private Boolean rememberMe;

    @SuppressWarnings("unused")
    public PlexUserUser id(Integer id) {

        this.id = id;
        return this;
    }

    /**
     * User ID
     *
     * @return id
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User ID")

    public Integer getId() {
        return id;
    }

    @SuppressWarnings("unused")
    public void setId(Integer id) {
        this.id = id;
    }

    @SuppressWarnings("unused")
    public PlexUserUser uuid(String uuid) {

        this.uuid = uuid;
        return this;
    }

    /**
     * User UUID
     *
     * @return uuid
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User UUID")

    public String getUuid() {
        return uuid;
    }

    @SuppressWarnings("unused")
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @SuppressWarnings("unused")
    public PlexUserUser email(String email) {

        this.email = email;
        return this;
    }

    /**
     * User email
     *
     * @return email
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User email")

    public String getEmail() {
        return email;
    }

    @SuppressWarnings("unused")
    public void setEmail(String email) {
        this.email = email;
    }

    @SuppressWarnings("unused")
    public PlexUserUser joinedAt(String joinedAt) {

        this.joinedAt = joinedAt;
        return this;
    }

    /**
     * Date user joined
     *
     * @return joinedAt
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Date user joined")

    public String getJoinedAt() {
        return joinedAt;
    }

    @SuppressWarnings("unused")
    public void setJoinedAt(String joinedAt) {
        this.joinedAt = joinedAt;
    }

    @SuppressWarnings("unused")
    public PlexUserUser username(String username) {

        this.username = username;
        return this;
    }

    /**
     * User username
     *
     * @return username
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User username")

    public String getUsername() {
        return username;
    }

    @SuppressWarnings("unused")
    public void setUsername(String username) {
        this.username = username;
    }

    @SuppressWarnings("unused")
    public PlexUserUser title(String title) {

        this.title = title;
        return this;
    }

    /**
     * User display name
     *
     * @return title
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User display name")

    public String getTitle() {
        return title;
    }

    @SuppressWarnings("unused")
    public void setTitle(String title) {
        this.title = title;
    }

    @SuppressWarnings("unused")
    public PlexUserUser thumb(URI thumb) {

        this.thumb = thumb;
        return this;
    }

    /**
     * User thumbnail link
     *
     * @return thumb
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User thumbnail link")

    public URI getThumb() {
        return thumb;
    }

    @SuppressWarnings("unused")
    public void setThumb(URI thumb) {
        this.thumb = thumb;
    }

    @SuppressWarnings("unused")
    public PlexUserUser authToken(String authToken) {

        this.authToken = authToken;
        return this;
    }

    /**
     * User auth token
     *
     * @return authToken
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User auth token")

    public String getAuthToken() {
        return authToken;
    }

    @SuppressWarnings("unused")
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    @SuppressWarnings("unused")
    public PlexUserUser authenticationToken(String authenticationToken) {

        this.authenticationToken = authenticationToken;
        return this;
    }

    /**
     * User auth token
     *
     * @return authenticationToken
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User auth token")

    public String getAuthenticationToken() {
        return authenticationToken;
    }

    @SuppressWarnings("unused")
    public void setAuthenticationToken(String authenticationToken) {
        this.authenticationToken = authenticationToken;
    }

    @SuppressWarnings("unused")
    public PlexUserUser subscription(PlexUserUserSubscription subscription) {

        this.subscription = subscription;
        return this;
    }

    /**
     * Get subscription
     *
     * @return subscription
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public PlexUserUserSubscription getSubscription() {
        return subscription;
    }

    @SuppressWarnings("unused")
    public void setSubscription(PlexUserUserSubscription subscription) {
        this.subscription = subscription;
    }

    @SuppressWarnings("unused")
    public PlexUserUser roles(PlexUserUserRoles roles) {

        this.roles = roles;
        return this;
    }

    /**
     * Get roles
     *
     * @return roles
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public PlexUserUserRoles getRoles() {
        return roles;
    }

    @SuppressWarnings("unused")
    public void setRoles(PlexUserUserRoles roles) {
        this.roles = roles;
    }

    @SuppressWarnings("unused")
    public PlexUserUser confirmedAt(String confirmedAt) {

        this.confirmedAt = confirmedAt;
        return this;
    }

    /**
     * User confirmation date
     *
     * @return confirmedAt
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User confirmation date")

    public String getConfirmedAt() {
        return confirmedAt;
    }

    @SuppressWarnings("unused")
    public void setConfirmedAt(String confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    @SuppressWarnings("unused")
    public PlexUserUser rememberMe(Boolean rememberMe) {

        this.rememberMe = rememberMe;
        return this;
    }

    /**
     * User remember login
     *
     * @return rememberMe
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User remember login")

    public Boolean getRememberMe() {
        return rememberMe;
    }

    @SuppressWarnings("unused")
    public void setRememberMe(Boolean rememberMe) {
        this.rememberMe = rememberMe;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlexUserUser plexUserUser = (PlexUserUser) o;
        return Objects.equals(this.id, plexUserUser.id) &&
                Objects.equals(this.uuid, plexUserUser.uuid) &&
                Objects.equals(this.email, plexUserUser.email) &&
                Objects.equals(this.joinedAt, plexUserUser.joinedAt) &&
                Objects.equals(this.username, plexUserUser.username) &&
                Objects.equals(this.title, plexUserUser.title) &&
                Objects.equals(this.thumb, plexUserUser.thumb) &&
                Objects.equals(this.authToken, plexUserUser.authToken) &&
                Objects.equals(this.authenticationToken,
                        plexUserUser.authenticationToken) &&
                Objects.equals(this.subscription, plexUserUser.subscription) &&
                Objects.equals(this.roles, plexUserUser.roles) &&
                Objects.equals(this.confirmedAt, plexUserUser.confirmedAt) &&
                Objects.equals(this.rememberMe, plexUserUser.rememberMe);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uuid, email, joinedAt, username, title, thumb,
                authToken, authenticationToken, subscription, roles,
                confirmedAt, rememberMe);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlexUserUser {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    joinedAt: ").append(toIndentedString(joinedAt)).append("\n");
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    thumb: ").append(toIndentedString(thumb)).append("\n");
        sb.append("    authToken: ")
                .append(toIndentedString(authToken))
                .append("\n");
        sb.append("    authenticationToken: ")
                .append(toIndentedString(authenticationToken))
                .append("\n");
        sb.append("    subscription: ")
                .append(toIndentedString(subscription))
                .append("\n");
        sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
        sb.append("    confirmedAt: ")
                .append(toIndentedString(confirmedAt))
                .append("\n");
        sb.append("    rememberMe: ")
                .append(toIndentedString(rememberMe))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
