/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * User subscription information
 */
@SuppressWarnings("unused")
@ApiModel(description = "User subscription information")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class PlexUserUserSubscription {
    public static final String SERIALIZED_NAME_ACTIVE = "active";
    public static final String SERIALIZED_NAME_STATUS = "status";
    public static final String SERIALIZED_NAME_PLAN = "plan";
    public static final String SERIALIZED_NAME_FEATURES = "features";
    @SerializedName(SERIALIZED_NAME_ACTIVE)
    private Boolean active;
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;
    @SerializedName(SERIALIZED_NAME_PLAN)
    private String plan;
    @SerializedName(SERIALIZED_NAME_FEATURES)
    private List<String> features = null;

    @SuppressWarnings("unused")
    public PlexUserUserSubscription active(Boolean active) {

        this.active = active;
        return this;
    }

    /**
     * Subscription active status
     *
     * @return active
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Subscription active status")

    public Boolean getActive() {
        return active;
    }

    @SuppressWarnings("unused")
    public void setActive(Boolean active) {
        this.active = active;
    }

    @SuppressWarnings("unused")
    public PlexUserUserSubscription status(String status) {

        this.status = status;
        return this;
    }

    /**
     * Subscription status
     *
     * @return status
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Subscription status")

    public String getStatus() {
        return status;
    }

    @SuppressWarnings("unused")
    public void setStatus(String status) {
        this.status = status;
    }

    @SuppressWarnings("unused")
    public PlexUserUserSubscription plan(String plan) {

        this.plan = plan;
        return this;
    }

    /**
     * Subscription plan
     *
     * @return plan
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Subscription plan")

    public String getPlan() {
        return plan;
    }

    @SuppressWarnings("unused")
    public void setPlan(String plan) {
        this.plan = plan;
    }

    @SuppressWarnings("unused")
    public PlexUserUserSubscription features(List<String> features) {

        this.features = features;
        return this;
    }

    @SuppressWarnings("unused")
    public PlexUserUserSubscription addFeaturesItem(String featuresItem) {
        if (this.features == null) {
            this.features = new ArrayList<>();
        }
        this.features.add(featuresItem);
        return this;
    }

    /**
     * Subscription features
     *
     * @return features
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Subscription features")

    public List<String> getFeatures() {
        return features;
    }

    @SuppressWarnings("unused")
    public void setFeatures(List<String> features) {
        this.features = features;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlexUserUserSubscription plexUserUserSubscription =
                (PlexUserUserSubscription) o;
        return Objects.equals(this.active, plexUserUserSubscription.active) &&
                Objects.equals(this.status, plexUserUserSubscription.status) &&
                Objects.equals(this.plan, plexUserUserSubscription.plan) &&
                Objects.equals(this.features, plexUserUserSubscription.features);
    }

    @Override
    public int hashCode() {
        return Objects.hash(active, status, plan, features);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlexUserUserSubscription {\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
        sb.append("    features: ").append(toIndentedString(features)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
