/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * PlexUserUser
 */

@SuppressWarnings("unused")
@Generated(value = "net.celestialdata.plexbot.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-23T04:57:45.670Z[GMT]")
public class PlexUserUser {
    @SerializedName("id")
    private Integer id = null;

    @SerializedName("uuid")
    private String uuid = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("joined_at")
    private String joinedAt = null;

    @SerializedName("username")
    private String username = null;

    @SerializedName("title")
    private String title = null;

    @SerializedName("thumb")
    private String thumb = null;

    @SerializedName("authToken")
    private String authToken = null;

    @SerializedName("authentication_token")
    private String authenticationToken = null;

    @SerializedName("subscription")
    private PlexUserUserSubscription subscription = null;

    @SerializedName("roles")
    private PlexUserUserRoles roles = null;

    @SerializedName("confirmedAt")
    private String confirmedAt = null;

    @SerializedName("rememberMe")
    private Boolean rememberMe = null;

    @SuppressWarnings("unused")
    public PlexUserUser id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * User ID
     *
     * @return id
     **/
    @SuppressWarnings("unused")
    public Integer getId() {
        return id;
    }

    @SuppressWarnings("unused")
    public void setId(Integer id) {
        this.id = id;
    }

    @SuppressWarnings("unused")
    public PlexUserUser uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * User UUID
     *
     * @return uuid
     **/
    @SuppressWarnings("unused")
    public String getUuid() {
        return uuid;
    }

    @SuppressWarnings("unused")
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @SuppressWarnings("unused")
    public PlexUserUser email(String email) {
        this.email = email;
        return this;
    }

    /**
     * User email
     *
     * @return email
     **/
    @SuppressWarnings("unused")
    public String getEmail() {
        return email;
    }

    @SuppressWarnings("unused")
    public void setEmail(String email) {
        this.email = email;
    }

    @SuppressWarnings("unused")
    public PlexUserUser joinedAt(String joinedAt) {
        this.joinedAt = joinedAt;
        return this;
    }

    /**
     * Date user joined
     *
     * @return joinedAt
     **/
    @SuppressWarnings("unused")
    public String getJoinedAt() {
        return joinedAt;
    }

    @SuppressWarnings("unused")
    public void setJoinedAt(String joinedAt) {
        this.joinedAt = joinedAt;
    }

    @SuppressWarnings("unused")
    public PlexUserUser username(String username) {
        this.username = username;
        return this;
    }

    /**
     * User username
     *
     * @return username
     **/
    @SuppressWarnings("unused")
    public String getUsername() {
        return username;
    }

    @SuppressWarnings("unused")
    public void setUsername(String username) {
        this.username = username;
    }

    @SuppressWarnings("unused")
    public PlexUserUser title(String title) {
        this.title = title;
        return this;
    }

    /**
     * User display name
     *
     * @return title
     **/
    @SuppressWarnings("unused")
    public String getTitle() {
        return title;
    }

    @SuppressWarnings("unused")
    public void setTitle(String title) {
        this.title = title;
    }

    @SuppressWarnings("unused")
    public PlexUserUser thumb(String thumb) {
        this.thumb = thumb;
        return this;
    }

    /**
     * User thumbnail link
     *
     * @return thumb
     **/
    @SuppressWarnings("unused")
    public String getThumb() {
        return thumb;
    }

    @SuppressWarnings("unused")
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    @SuppressWarnings("unused")
    public PlexUserUser authToken(String authToken) {
        this.authToken = authToken;
        return this;
    }

    /**
     * User auth token
     *
     * @return authToken
     **/
    @SuppressWarnings("unused")
    public String getAuthToken() {
        return authToken;
    }

    @SuppressWarnings("unused")
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    @SuppressWarnings("unused")
    public PlexUserUser authenticationToken(String authenticationToken) {
        this.authenticationToken = authenticationToken;
        return this;
    }

    /**
     * User auth token
     *
     * @return authenticationToken
     **/
    @SuppressWarnings("unused")
    public String getAuthenticationToken() {
        return authenticationToken;
    }

    @SuppressWarnings("unused")
    public void setAuthenticationToken(String authenticationToken) {
        this.authenticationToken = authenticationToken;
    }

    @SuppressWarnings("unused")
    public PlexUserUser subscription(PlexUserUserSubscription subscription) {
        this.subscription = subscription;
        return this;
    }

    /**
     * Get subscription
     *
     * @return subscription
     **/
    @SuppressWarnings("unused")
    public PlexUserUserSubscription getSubscription() {
        return subscription;
    }

    @SuppressWarnings("unused")
    public void setSubscription(PlexUserUserSubscription subscription) {
        this.subscription = subscription;
    }

    @SuppressWarnings("unused")
    public PlexUserUser roles(PlexUserUserRoles roles) {
        this.roles = roles;
        return this;
    }

    /**
     * Get roles
     *
     * @return roles
     **/
    @SuppressWarnings("unused")
    public PlexUserUserRoles getRoles() {
        return roles;
    }

    @SuppressWarnings("unused")
    public void setRoles(PlexUserUserRoles roles) {
        this.roles = roles;
    }

    @SuppressWarnings("unused")
    public PlexUserUser confirmedAt(String confirmedAt) {
        this.confirmedAt = confirmedAt;
        return this;
    }

    /**
     * User confirmation date
     *
     * @return confirmedAt
     **/
    @SuppressWarnings("unused")
    public String getConfirmedAt() {
        return confirmedAt;
    }

    @SuppressWarnings("unused")
    public void setConfirmedAt(String confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    @SuppressWarnings("unused")
    public PlexUserUser rememberMe(Boolean rememberMe) {
        this.rememberMe = rememberMe;
        return this;
    }

    /**
     * User remember login
     *
     * @return rememberMe
     **/
    @SuppressWarnings("unused")
    public Boolean isRememberMe() {
        return rememberMe;
    }

    @SuppressWarnings("unused")
    public void setRememberMe(Boolean rememberMe) {
        this.rememberMe = rememberMe;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlexUserUser plexUserUser = (PlexUserUser) o;
        return Objects.equals(this.id, plexUserUser.id) &&
                Objects.equals(this.uuid, plexUserUser.uuid) &&
                Objects.equals(this.email, plexUserUser.email) &&
                Objects.equals(this.joinedAt, plexUserUser.joinedAt) &&
                Objects.equals(this.username, plexUserUser.username) &&
                Objects.equals(this.title, plexUserUser.title) &&
                Objects.equals(this.thumb, plexUserUser.thumb) &&
                Objects.equals(this.authToken, plexUserUser.authToken) &&
                Objects.equals(this.authenticationToken, plexUserUser.authenticationToken) &&
                Objects.equals(this.subscription, plexUserUser.subscription) &&
                Objects.equals(this.roles, plexUserUser.roles) &&
                Objects.equals(this.confirmedAt, plexUserUser.confirmedAt) &&
                Objects.equals(this.rememberMe, plexUserUser.rememberMe);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uuid, email, joinedAt, username, title, thumb, authToken, authenticationToken, subscription, roles, confirmedAt, rememberMe);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlexUserUser {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    joinedAt: ").append(toIndentedString(joinedAt)).append("\n");
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    thumb: ").append(toIndentedString(thumb)).append("\n");
        sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
        sb.append("    authenticationToken: ").append(toIndentedString(authenticationToken)).append("\n");
        sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
        sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
        sb.append("    confirmedAt: ").append(toIndentedString(confirmedAt)).append("\n");
        sb.append("    rememberMe: ").append(toIndentedString(rememberMe)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
