/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * User roles
 */
@SuppressWarnings("unused")
@Generated(value = "net.celestialdata.plexbot.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-23T04:57:45.670Z[GMT]")
public class PlexUserUserRoles {
    @SerializedName("roles")
    private List<String> roles = null;

    @SuppressWarnings("unused")
    public PlexUserUserRoles roles(List<String> roles) {
        this.roles = roles;
        return this;
    }

    @SuppressWarnings("unused")
    public PlexUserUserRoles addRolesItem(String rolesItem) {
        if (this.roles == null) {
            this.roles = new ArrayList<String>();
        }
        this.roles.add(rolesItem);
        return this;
    }

    /**
     * List of user roles
     *
     * @return roles
     **/
    @SuppressWarnings("unused")
    public List<String> getRoles() {
        return roles;
    }

    @SuppressWarnings("unused")
    public void setRoles(List<String> roles) {
        this.roles = roles;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlexUserUserRoles plexUserUserRoles = (PlexUserUserRoles) o;
        return Objects.equals(this.roles, plexUserUserRoles.roles);
    }

    @Override
    public int hashCode() {
        return Objects.hash(roles);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlexUserUserRoles {\n");

        sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
