/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * Response generated when adding a magnet link
 */
@Schema(description = "Response generated when adding a magnet link")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-18T04:51:41.119Z[GMT]")
public class RdbMagnetLink {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  public RdbMagnetLink id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the created torrent
   * @return id
  **/
  @Schema(description = "ID of the created torrent")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RdbMagnetLink uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * URL of the created torrent
   * @return uri
  **/
  @Schema(description = "URL of the created torrent")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RdbMagnetLink rdbMagnetLink = (RdbMagnetLink) o;
    return Objects.equals(this.id, rdbMagnetLink.id) &&
        Objects.equals(this.uri, rdbMagnetLink.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RdbMagnetLink {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
