/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DTO to select which files for RDB to download
 */
@SuppressWarnings("unused")
@ApiModel(description = "DTO to select which files for RDB to download")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class RdbSelectFiles {
    public static final String SERIALIZED_NAME_FILES = "files";
    @SerializedName(SERIALIZED_NAME_FILES)
    private String files;

    @SuppressWarnings("unused")
    public RdbSelectFiles files(String files) {

        this.files = files;
        return this;
    }

    /**
     * Selected files IDs (comma separated) or \&quot;all\&quot;
     *
     * @return files
     **/
    @SuppressWarnings("unused")
    @ApiModelProperty(required = true,
            value = "Selected files IDs (comma separated) or \"all\"")

    public String
    getFiles() {
        return files;
    }

    @SuppressWarnings("unused")
    public void setFiles(String files) {
        this.files = files;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RdbSelectFiles rdbSelectFiles = (RdbSelectFiles) o;
        return Objects.equals(this.files, rdbSelectFiles.files);
    }

    @Override
    public int hashCode() {
        return Objects.hash(files);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RdbSelectFiles {\n");
        sb.append("    files: ").append(toIndentedString(files)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
