/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * search result
 */
@ApiModel(description = "search result")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-04-15T16:42:07.120298-05:00[America/Chicago]")
public class SearchResult {
    public static final String SERIALIZED_NAME_ALIASES = "aliases";
    public static final String SERIALIZED_NAME_COMPANIES = "companies";
    public static final String SERIALIZED_NAME_COMPANY_TYPE = "companyType";
    public static final String SERIALIZED_NAME_COUNTRY = "country";
    public static final String SERIALIZED_NAME_DIRECTOR = "director";
    public static final String SERIALIZED_NAME_EXTENDED_TITLE = "extendedTitle";
    public static final String SERIALIZED_NAME_GENRES = "genres";
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static final String SERIALIZED_NAME_NAME_TRANSLATED = "nameTranslated";
    public static final String SERIALIZED_NAME_NETWORK = "network";
    public static final String SERIALIZED_NAME_OFFICIAL_LIST = "officialList";
    public static final String SERIALIZED_NAME_OVERVIEW = "overview";
    public static final String SERIALIZED_NAME_OVERVIEW_TRANSLATED =
            "overview_translated";
    public static final String SERIALIZED_NAME_POSTERS = "posters";
    public static final String SERIALIZED_NAME_PRIMARY_LANGUAGE =
            "primaryLanguage";
    public static final String SERIALIZED_NAME_PRIMARY_TYPE = "primaryType";
    public static final String SERIALIZED_NAME_STATUS = "status";
    public static final String SERIALIZED_NAME_TRANSLATIONS_WITH_LANG =
            "translationsWithLang";
    public static final String SERIALIZED_NAME_TVDB_ID = "tvdb_id";
    public static final String SERIALIZED_NAME_TYPE = "type";
    public static final String SERIALIZED_NAME_YEAR = "year";
    @SerializedName(SERIALIZED_NAME_ALIASES)
    private List<String> aliases = null;
    @SerializedName(SERIALIZED_NAME_COMPANIES)
    private List<String> companies = null;
    @SerializedName(SERIALIZED_NAME_COMPANY_TYPE)
    private String companyType;
    @SerializedName(SERIALIZED_NAME_COUNTRY)
    private String country;
    @SerializedName(SERIALIZED_NAME_DIRECTOR)
    private String director;
    @SerializedName(SERIALIZED_NAME_EXTENDED_TITLE)
    private String extendedTitle;
    @SerializedName(SERIALIZED_NAME_GENRES)
    private List<String> genres = null;
    @SerializedName(SERIALIZED_NAME_ID)
    private String id;
    @SerializedName(SERIALIZED_NAME_IMAGE_URL)
    private String imageUrl;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_NAME_TRANSLATED)
    private String nameTranslated;
    @SerializedName(SERIALIZED_NAME_NETWORK)
    private String network;
    @SerializedName(SERIALIZED_NAME_OFFICIAL_LIST)
    private String officialList;
    @SerializedName(SERIALIZED_NAME_OVERVIEW)
    private String overview;
    @SerializedName(SERIALIZED_NAME_OVERVIEW_TRANSLATED)
    private List<String> overviewTranslated = null;
    @SerializedName(SERIALIZED_NAME_POSTERS)
    private List<String> posters = null;
    @SerializedName(SERIALIZED_NAME_PRIMARY_LANGUAGE)
    private String primaryLanguage;
    @SerializedName(SERIALIZED_NAME_PRIMARY_TYPE)
    private String primaryType;
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;
    @SerializedName(SERIALIZED_NAME_TRANSLATIONS_WITH_LANG)
    private List<String> translationsWithLang = null;
    @SerializedName(SERIALIZED_NAME_TVDB_ID)
    private String tvdbId;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;
    @SerializedName(SERIALIZED_NAME_YEAR)
    private String year;

    public SearchResult aliases(List<String> aliases) {

        this.aliases = aliases;
        return this;
    }

    public SearchResult addAliasesItem(String aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getAliases() {
        return aliases;
    }

    public void setAliases(List<String> aliases) {
        this.aliases = aliases;
    }

    public SearchResult companies(List<String> companies) {

        this.companies = companies;
        return this;
    }

    public SearchResult addCompaniesItem(String companiesItem) {
        if (this.companies == null) {
            this.companies = new ArrayList<>();
        }
        this.companies.add(companiesItem);
        return this;
    }

    /**
     * Get companies
     *
     * @return companies
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getCompanies() {
        return companies;
    }

    public void setCompanies(List<String> companies) {
        this.companies = companies;
    }

    public SearchResult companyType(String companyType) {

        this.companyType = companyType;
        return this;
    }

    /**
     * Get companyType
     *
     * @return companyType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getCompanyType() {
        return companyType;
    }

    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    public SearchResult country(String country) {

        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public SearchResult director(String director) {

        this.director = director;
        return this;
    }

    /**
     * Get director
     *
     * @return director
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public SearchResult extendedTitle(String extendedTitle) {

        this.extendedTitle = extendedTitle;
        return this;
    }

    /**
     * Get extendedTitle
     *
     * @return extendedTitle
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getExtendedTitle() {
        return extendedTitle;
    }

    public void setExtendedTitle(String extendedTitle) {
        this.extendedTitle = extendedTitle;
    }

    public SearchResult genres(List<String> genres) {

        this.genres = genres;
        return this;
    }

    public SearchResult addGenresItem(String genresItem) {
        if (this.genres == null) {
            this.genres = new ArrayList<>();
        }
        this.genres.add(genresItem);
        return this;
    }

    /**
     * Get genres
     *
     * @return genres
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getGenres() {
        return genres;
    }

    public void setGenres(List<String> genres) {
        this.genres = genres;
    }

    public SearchResult id(String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SearchResult imageUrl(String imageUrl) {

        this.imageUrl = imageUrl;
        return this;
    }

    /**
     * Get imageUrl
     *
     * @return imageUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public SearchResult name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SearchResult nameTranslated(String nameTranslated) {

        this.nameTranslated = nameTranslated;
        return this;
    }

    /**
     * Get nameTranslated
     *
     * @return nameTranslated
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getNameTranslated() {
        return nameTranslated;
    }

    public void setNameTranslated(String nameTranslated) {
        this.nameTranslated = nameTranslated;
    }

    public SearchResult network(String network) {

        this.network = network;
        return this;
    }

    /**
     * Get network
     *
     * @return network
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getNetwork() {
        return network;
    }

    public void setNetwork(String network) {
        this.network = network;
    }

    public SearchResult officialList(String officialList) {

        this.officialList = officialList;
        return this;
    }

    /**
     * Get officialList
     *
     * @return officialList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getOfficialList() {
        return officialList;
    }

    public void setOfficialList(String officialList) {
        this.officialList = officialList;
    }

    public SearchResult overview(String overview) {

        this.overview = overview;
        return this;
    }

    /**
     * Get overview
     *
     * @return overview
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public SearchResult overviewTranslated(List<String> overviewTranslated) {

        this.overviewTranslated = overviewTranslated;
        return this;
    }

    public SearchResult addOverviewTranslatedItem(String overviewTranslatedItem) {
        if (this.overviewTranslated == null) {
            this.overviewTranslated = new ArrayList<>();
        }
        this.overviewTranslated.add(overviewTranslatedItem);
        return this;
    }

    /**
     * Get overviewTranslated
     *
     * @return overviewTranslated
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getOverviewTranslated() {
        return overviewTranslated;
    }

    public void setOverviewTranslated(List<String> overviewTranslated) {
        this.overviewTranslated = overviewTranslated;
    }

    public SearchResult posters(List<String> posters) {

        this.posters = posters;
        return this;
    }

    public SearchResult addPostersItem(String postersItem) {
        if (this.posters == null) {
            this.posters = new ArrayList<>();
        }
        this.posters.add(postersItem);
        return this;
    }

    /**
     * Get posters
     *
     * @return posters
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getPosters() {
        return posters;
    }

    public void setPosters(List<String> posters) {
        this.posters = posters;
    }

    public SearchResult primaryLanguage(String primaryLanguage) {

        this.primaryLanguage = primaryLanguage;
        return this;
    }

    /**
     * Get primaryLanguage
     *
     * @return primaryLanguage
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPrimaryLanguage() {
        return primaryLanguage;
    }

    public void setPrimaryLanguage(String primaryLanguage) {
        this.primaryLanguage = primaryLanguage;
    }

    public SearchResult primaryType(String primaryType) {

        this.primaryType = primaryType;
        return this;
    }

    /**
     * Get primaryType
     *
     * @return primaryType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPrimaryType() {
        return primaryType;
    }

    public void setPrimaryType(String primaryType) {
        this.primaryType = primaryType;
    }

    public SearchResult status(String status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public SearchResult translationsWithLang(List<String> translationsWithLang) {

        this.translationsWithLang = translationsWithLang;
        return this;
    }

    public SearchResult
    addTranslationsWithLangItem(String translationsWithLangItem) {
        if (this.translationsWithLang == null) {
            this.translationsWithLang = new ArrayList<>();
        }
        this.translationsWithLang.add(translationsWithLangItem);
        return this;
    }

    /**
     * Get translationsWithLang
     *
     * @return translationsWithLang
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getTranslationsWithLang() {
        return translationsWithLang;
    }

    public void setTranslationsWithLang(List<String> translationsWithLang) {
        this.translationsWithLang = translationsWithLang;
    }

    public SearchResult tvdbId(String tvdbId) {

        this.tvdbId = tvdbId;
        return this;
    }

    /**
     * Get tvdbId
     *
     * @return tvdbId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTvdbId() {
        return tvdbId;
    }

    public void setTvdbId(String tvdbId) {
        this.tvdbId = tvdbId;
    }

    public SearchResult type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public SearchResult year(String year) {

        this.year = year;
        return this;
    }

    /**
     * Get year
     *
     * @return year
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchResult searchResult = (SearchResult) o;
        return Objects.equals(this.aliases, searchResult.aliases) &&
                Objects.equals(this.companies, searchResult.companies) &&
                Objects.equals(this.companyType, searchResult.companyType) &&
                Objects.equals(this.country, searchResult.country) &&
                Objects.equals(this.director, searchResult.director) &&
                Objects.equals(this.extendedTitle, searchResult.extendedTitle) &&
                Objects.equals(this.genres, searchResult.genres) &&
                Objects.equals(this.id, searchResult.id) &&
                Objects.equals(this.imageUrl, searchResult.imageUrl) &&
                Objects.equals(this.name, searchResult.name) &&
                Objects.equals(this.nameTranslated, searchResult.nameTranslated) &&
                Objects.equals(this.network, searchResult.network) &&
                Objects.equals(this.officialList, searchResult.officialList) &&
                Objects.equals(this.overview, searchResult.overview) &&
                Objects.equals(this.overviewTranslated,
                        searchResult.overviewTranslated) &&
                Objects.equals(this.posters, searchResult.posters) &&
                Objects.equals(this.primaryLanguage, searchResult.primaryLanguage) &&
                Objects.equals(this.primaryType, searchResult.primaryType) &&
                Objects.equals(this.status, searchResult.status) &&
                Objects.equals(this.translationsWithLang,
                        searchResult.translationsWithLang) &&
                Objects.equals(this.tvdbId, searchResult.tvdbId) &&
                Objects.equals(this.type, searchResult.type) &&
                Objects.equals(this.year, searchResult.year);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                aliases, companies, companyType, country, director, extendedTitle,
                genres, id, imageUrl, name, nameTranslated, network, officialList,
                overview, overviewTranslated, posters, primaryLanguage, primaryType,
                status, translationsWithLang, tvdbId, type, year);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchResult {\n");
        sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
        sb.append("    companies: ")
                .append(toIndentedString(companies))
                .append("\n");
        sb.append("    companyType: ")
                .append(toIndentedString(companyType))
                .append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    director: ").append(toIndentedString(director)).append("\n");
        sb.append("    extendedTitle: ")
                .append(toIndentedString(extendedTitle))
                .append("\n");
        sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    nameTranslated: ")
                .append(toIndentedString(nameTranslated))
                .append("\n");
        sb.append("    network: ").append(toIndentedString(network)).append("\n");
        sb.append("    officialList: ")
                .append(toIndentedString(officialList))
                .append("\n");
        sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
        sb.append("    overviewTranslated: ")
                .append(toIndentedString(overviewTranslated))
                .append("\n");
        sb.append("    posters: ").append(toIndentedString(posters)).append("\n");
        sb.append("    primaryLanguage: ")
                .append(toIndentedString(primaryLanguage))
                .append("\n");
        sb.append("    primaryType: ")
                .append(toIndentedString(primaryType))
                .append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    translationsWithLang: ")
                .append(toIndentedString(translationsWithLang))
                .append("\n");
        sb.append("    tvdbId: ").append(toIndentedString(tvdbId)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
