/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Response data for a list of episodes for a series
 */
@ApiModel(description = "Response data for a list of episodes for a series")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-04-15T16:42:07.120298-05:00[America/Chicago]")
public class SeriesEpisodesResponse {
    public static final String SERIALIZED_NAME_SERIES = "series";
    public static final String SERIALIZED_NAME_EPISODES = "episodes";
    @SerializedName(SERIALIZED_NAME_SERIES)
    private SeriesExtendedRecord series;
    @SerializedName(SERIALIZED_NAME_EPISODES)
    private List<EpisodeBaseRecord> episodes = null;

    public SeriesEpisodesResponse series(SeriesExtendedRecord series) {

        this.series = series;
        return this;
    }

    /**
     * Get series
     *
     * @return series
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public SeriesExtendedRecord getSeries() {
        return series;
    }

    public void setSeries(SeriesExtendedRecord series) {
        this.series = series;
    }

    public SeriesEpisodesResponse episodes(List<EpisodeBaseRecord> episodes) {

        this.episodes = episodes;
        return this;
    }

    public SeriesEpisodesResponse
    addEpisodesItem(EpisodeBaseRecord episodesItem) {
        if (this.episodes == null) {
            this.episodes = new ArrayList<>();
        }
        this.episodes.add(episodesItem);
        return this;
    }

    /**
     * Get episodes
     *
     * @return episodes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<EpisodeBaseRecord> getEpisodes() {
        return episodes;
    }

    public void setEpisodes(List<EpisodeBaseRecord> episodes) {
        this.episodes = episodes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SeriesEpisodesResponse seriesEpisodesResponse = (SeriesEpisodesResponse) o;
        return Objects.equals(this.series, seriesEpisodesResponse.series) &&
                Objects.equals(this.episodes, seriesEpisodesResponse.episodes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(series, episodes);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SeriesEpisodesResponse {\n");
        sb.append("    series: ").append(toIndentedString(series)).append("\n");
        sb.append("    episodes: ").append(toIndentedString(episodes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
