/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The base record for a series
 */
@ApiModel(description = "The base record for a series")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-04-15T16:42:07.120298-05:00[America/Chicago]")
public class SeriesBaseRecord {
    public static final String SERIALIZED_NAME_ABBREVIATION = "abbreviation";
    public static final String SERIALIZED_NAME_ALIASES = "aliases";
    public static final String SERIALIZED_NAME_COUNTRY = "country";
    public static final String SERIALIZED_NAME_DEFAULT_SEASON_TYPE =
            "defaultSeasonType";
    public static final String SERIALIZED_NAME_FIRST_AIRED = "firstAired";
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_IMAGE = "image";
    public static final String SERIALIZED_NAME_IS_ORDER_RANDOMIZED =
            "isOrderRandomized";
    public static final String SERIALIZED_NAME_LAST_AIRED = "lastAired";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static final String SERIALIZED_NAME_NAME_TRANSLATIONS =
            "nameTranslations";
    public static final String SERIALIZED_NAME_NEXT_AIRED = "nextAired";
    public static final String SERIALIZED_NAME_ORIGINAL_COUNTRY =
            "originalCountry";
    public static final String SERIALIZED_NAME_ORIGINAL_LANGUAGE =
            "originalLanguage";
    public static final String SERIALIZED_NAME_OVERVIEW_TRANSLATIONS =
            "overviewTranslations";
    public static final String SERIALIZED_NAME_SCORE = "score";
    public static final String SERIALIZED_NAME_SLUG = "slug";
    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_ABBREVIATION)
    private String abbreviation;
    @SerializedName(SERIALIZED_NAME_ALIASES)
    private List<Alias> aliases = null;
    @SerializedName(SERIALIZED_NAME_COUNTRY)
    private String country;
    @SerializedName(SERIALIZED_NAME_DEFAULT_SEASON_TYPE)
    private Long defaultSeasonType;
    @SerializedName(SERIALIZED_NAME_FIRST_AIRED)
    private String firstAired;
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    @SerializedName(SERIALIZED_NAME_IMAGE)
    private String image;
    @SerializedName(SERIALIZED_NAME_IS_ORDER_RANDOMIZED)
    private Boolean isOrderRandomized;
    @SerializedName(SERIALIZED_NAME_LAST_AIRED)
    private String lastAired;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_NAME_TRANSLATIONS)
    private List<String> nameTranslations = null;
    @SerializedName(SERIALIZED_NAME_NEXT_AIRED)
    private String nextAired;
    @SerializedName(SERIALIZED_NAME_ORIGINAL_COUNTRY)
    private String originalCountry;
    @SerializedName(SERIALIZED_NAME_ORIGINAL_LANGUAGE)
    private String originalLanguage;
    @SerializedName(SERIALIZED_NAME_OVERVIEW_TRANSLATIONS)
    private List<String> overviewTranslations = null;
    @SerializedName(SERIALIZED_NAME_SCORE)
    private Double score;
    @SerializedName(SERIALIZED_NAME_SLUG)
    private String slug;
    @SerializedName(SERIALIZED_NAME_STATUS)
    private Status status;

    public SeriesBaseRecord abbreviation(String abbreviation) {

        this.abbreviation = abbreviation;
        return this;
    }

    /**
     * Get abbreviation
     *
     * @return abbreviation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public SeriesBaseRecord aliases(List<Alias> aliases) {

        this.aliases = aliases;
        return this;
    }

    public SeriesBaseRecord addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public SeriesBaseRecord country(String country) {

        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public SeriesBaseRecord defaultSeasonType(Long defaultSeasonType) {

        this.defaultSeasonType = defaultSeasonType;
        return this;
    }

    /**
     * Get defaultSeasonType
     *
     * @return defaultSeasonType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Long getDefaultSeasonType() {
        return defaultSeasonType;
    }

    public void setDefaultSeasonType(Long defaultSeasonType) {
        this.defaultSeasonType = defaultSeasonType;
    }

    public SeriesBaseRecord firstAired(String firstAired) {

        this.firstAired = firstAired;
        return this;
    }

    /**
     * Get firstAired
     *
     * @return firstAired
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFirstAired() {
        return firstAired;
    }

    public void setFirstAired(String firstAired) {
        this.firstAired = firstAired;
    }

    public SeriesBaseRecord id(Integer id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public SeriesBaseRecord image(String image) {

        this.image = image;
        return this;
    }

    /**
     * Get image
     *
     * @return image
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public SeriesBaseRecord isOrderRandomized(Boolean isOrderRandomized) {

        this.isOrderRandomized = isOrderRandomized;
        return this;
    }

    /**
     * Get isOrderRandomized
     *
     * @return isOrderRandomized
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getIsOrderRandomized() {
        return isOrderRandomized;
    }

    public void setIsOrderRandomized(Boolean isOrderRandomized) {
        this.isOrderRandomized = isOrderRandomized;
    }

    public SeriesBaseRecord lastAired(String lastAired) {

        this.lastAired = lastAired;
        return this;
    }

    /**
     * Get lastAired
     *
     * @return lastAired
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLastAired() {
        return lastAired;
    }

    public void setLastAired(String lastAired) {
        this.lastAired = lastAired;
    }

    public SeriesBaseRecord name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SeriesBaseRecord nameTranslations(List<String> nameTranslations) {

        this.nameTranslations = nameTranslations;
        return this;
    }

    public SeriesBaseRecord addNameTranslationsItem(String nameTranslationsItem) {
        if (this.nameTranslations == null) {
            this.nameTranslations = new ArrayList<>();
        }
        this.nameTranslations.add(nameTranslationsItem);
        return this;
    }

    /**
     * Get nameTranslations
     *
     * @return nameTranslations
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getNameTranslations() {
        return nameTranslations;
    }

    public void setNameTranslations(List<String> nameTranslations) {
        this.nameTranslations = nameTranslations;
    }

    public SeriesBaseRecord nextAired(String nextAired) {

        this.nextAired = nextAired;
        return this;
    }

    /**
     * Get nextAired
     *
     * @return nextAired
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getNextAired() {
        return nextAired;
    }

    public void setNextAired(String nextAired) {
        this.nextAired = nextAired;
    }

    public SeriesBaseRecord originalCountry(String originalCountry) {

        this.originalCountry = originalCountry;
        return this;
    }

    /**
     * Get originalCountry
     *
     * @return originalCountry
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getOriginalCountry() {
        return originalCountry;
    }

    public void setOriginalCountry(String originalCountry) {
        this.originalCountry = originalCountry;
    }

    public SeriesBaseRecord originalLanguage(String originalLanguage) {

        this.originalLanguage = originalLanguage;
        return this;
    }

    /**
     * Get originalLanguage
     *
     * @return originalLanguage
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getOriginalLanguage() {
        return originalLanguage;
    }

    public void setOriginalLanguage(String originalLanguage) {
        this.originalLanguage = originalLanguage;
    }

    public SeriesBaseRecord
    overviewTranslations(List<String> overviewTranslations) {

        this.overviewTranslations = overviewTranslations;
        return this;
    }

    public SeriesBaseRecord
    addOverviewTranslationsItem(String overviewTranslationsItem) {
        if (this.overviewTranslations == null) {
            this.overviewTranslations = new ArrayList<>();
        }
        this.overviewTranslations.add(overviewTranslationsItem);
        return this;
    }

    /**
     * Get overviewTranslations
     *
     * @return overviewTranslations
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getOverviewTranslations() {
        return overviewTranslations;
    }

    public void setOverviewTranslations(List<String> overviewTranslations) {
        this.overviewTranslations = overviewTranslations;
    }

    public SeriesBaseRecord score(Double score) {

        this.score = score;
        return this;
    }

    /**
     * Get score
     *
     * @return score
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public SeriesBaseRecord slug(String slug) {

        this.slug = slug;
        return this;
    }

    /**
     * Get slug
     *
     * @return slug
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public SeriesBaseRecord status(Status status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SeriesBaseRecord seriesBaseRecord = (SeriesBaseRecord) o;
        return Objects.equals(this.abbreviation, seriesBaseRecord.abbreviation) &&
                Objects.equals(this.aliases, seriesBaseRecord.aliases) &&
                Objects.equals(this.country, seriesBaseRecord.country) &&
                Objects.equals(this.defaultSeasonType,
                        seriesBaseRecord.defaultSeasonType) &&
                Objects.equals(this.firstAired, seriesBaseRecord.firstAired) &&
                Objects.equals(this.id, seriesBaseRecord.id) &&
                Objects.equals(this.image, seriesBaseRecord.image) &&
                Objects.equals(this.isOrderRandomized,
                        seriesBaseRecord.isOrderRandomized) &&
                Objects.equals(this.lastAired, seriesBaseRecord.lastAired) &&
                Objects.equals(this.name, seriesBaseRecord.name) &&
                Objects.equals(this.nameTranslations,
                        seriesBaseRecord.nameTranslations) &&
                Objects.equals(this.nextAired, seriesBaseRecord.nextAired) &&
                Objects.equals(this.originalCountry,
                        seriesBaseRecord.originalCountry) &&
                Objects.equals(this.originalLanguage,
                        seriesBaseRecord.originalLanguage) &&
                Objects.equals(this.overviewTranslations,
                        seriesBaseRecord.overviewTranslations) &&
                Objects.equals(this.score, seriesBaseRecord.score) &&
                Objects.equals(this.slug, seriesBaseRecord.slug) &&
                Objects.equals(this.status, seriesBaseRecord.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(abbreviation, aliases, country, defaultSeasonType,
                firstAired, id, image, isOrderRandomized, lastAired,
                name, nameTranslations, nextAired, originalCountry,
                originalLanguage, overviewTranslations, score, slug,
                status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SeriesBaseRecord {\n");
        sb.append("    abbreviation: ")
                .append(toIndentedString(abbreviation))
                .append("\n");
        sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    defaultSeasonType: ")
                .append(toIndentedString(defaultSeasonType))
                .append("\n");
        sb.append("    firstAired: ")
                .append(toIndentedString(firstAired))
                .append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    image: ").append(toIndentedString(image)).append("\n");
        sb.append("    isOrderRandomized: ")
                .append(toIndentedString(isOrderRandomized))
                .append("\n");
        sb.append("    lastAired: ")
                .append(toIndentedString(lastAired))
                .append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    nameTranslations: ")
                .append(toIndentedString(nameTranslations))
                .append("\n");
        sb.append("    nextAired: ")
                .append(toIndentedString(nextAired))
                .append("\n");
        sb.append("    originalCountry: ")
                .append(toIndentedString(originalCountry))
                .append("\n");
        sb.append("    originalLanguage: ")
                .append(toIndentedString(originalLanguage))
                .append("\n");
        sb.append("    overviewTranslations: ")
                .append(toIndentedString(overviewTranslations))
                .append("\n");
        sb.append("    score: ").append(toIndentedString(score)).append("\n");
        sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
