/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * tag option record
 */
@ApiModel(description = "tag option record")
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-04-15T16:42:07.120298-05:00[America/Chicago]")
public class TagOption {
    public static final String SERIALIZED_NAME_HELP_TEXT = "helpText";
    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static final String SERIALIZED_NAME_TAG = "tag";
    public static final String SERIALIZED_NAME_TAG_NAME = "tagName";
    @SerializedName(SERIALIZED_NAME_HELP_TEXT)
    private String helpText;
    @SerializedName(SERIALIZED_NAME_ID)
    private Long id;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_TAG)
    private Long tag;
    @SerializedName(SERIALIZED_NAME_TAG_NAME)
    private String tagName;

    public TagOption helpText(String helpText) {

        this.helpText = helpText;
        return this;
    }

    /**
     * Get helpText
     *
     * @return helpText
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getHelpText() {
        return helpText;
    }

    public void setHelpText(String helpText) {
        this.helpText = helpText;
    }

    public TagOption id(Long id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TagOption name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TagOption tag(Long tag) {

        this.tag = tag;
        return this;
    }

    /**
     * Get tag
     *
     * @return tag
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Long getTag() {
        return tag;
    }

    public void setTag(Long tag) {
        this.tag = tag;
    }

    public TagOption tagName(String tagName) {

        this.tagName = tagName;
        return this;
    }

    /**
     * Get tagName
     *
     * @return tagName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTagName() {
        return tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TagOption tagOption = (TagOption) o;
        return Objects.equals(this.helpText, tagOption.helpText) &&
                Objects.equals(this.id, tagOption.id) &&
                Objects.equals(this.name, tagOption.name) &&
                Objects.equals(this.tag, tagOption.tag) &&
                Objects.equals(this.tagName, tagOption.tagName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(helpText, id, name, tag, tagName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TagOption {\n");
        sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("    tagName: ").append(toIndentedString(tagName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
