/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * Base response of request to YTS
 */
@Schema(description = "Base response of request to YTS")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-18T04:51:41.119Z[GMT]")
public class YtsBaseResponse {
  @SerializedName("status")
  private String status = null;

  @SerializedName("status_message")
  private String statusMessage = null;

  @SerializedName("data")
  private OneOfYtsBaseResponseData data = null;

  public YtsBaseResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Request status
   * @return status
  **/
  @Schema(description = "Request status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public YtsBaseResponse statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Request status message
   * @return statusMessage
  **/
  @Schema(description = "Request status message")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public YtsBaseResponse data(OneOfYtsBaseResponseData data) {
    this.data = data;
    return this;
  }

   /**
   * Data for the request
   * @return data
  **/
  @Schema(description = "Data for the request")
  public OneOfYtsBaseResponseData getData() {
    return data;
  }

  public void setData(OneOfYtsBaseResponseData data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YtsBaseResponse ytsBaseResponse = (YtsBaseResponse) o;
    return Objects.equals(this.status, ytsBaseResponse.status) &&
        Objects.equals(this.statusMessage, ytsBaseResponse.statusMessage) &&
        Objects.equals(this.data, ytsBaseResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, statusMessage, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YtsBaseResponse {\n");

    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
