/*
 * Plexbot
 * Provides all the API functions necessary for the Plexbot to function.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: brandan.schmitz@celestialdata.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package net.celestialdata.plexbot.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * YtsTorrentInfo
 */
@javax.annotation.
        Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2021-02-18T23:30:04.504837-06:00[America/Chicago]")
public class YtsTorrentInfo {
    public static final String SERIALIZED_NAME_URL = "url";
    public static final String SERIALIZED_NAME_HASH = "hash";
    public static final String SERIALIZED_NAME_QUALITY = "quality";
    public static final String SERIALIZED_NAME_TYPE = "type";
    public static final String SERIALIZED_NAME_SEEDS = "seeds";
    public static final String SERIALIZED_NAME_PEERS = "peers";
    public static final String SERIALIZED_NAME_SIZE = "size";
    public static final String SERIALIZED_NAME_SIZE_BYTES = "size_bytes";
    public static final String SERIALIZED_NAME_DATE_UPLOADED = "date_uploaded";
    public static final String SERIALIZED_NAME_DATE_UPLOADED_UNIX =
            "date_uploaded_unix";
    @SerializedName(SERIALIZED_NAME_URL)
    private String url;
    @SerializedName(SERIALIZED_NAME_HASH)
    private String hash;
    @SerializedName(SERIALIZED_NAME_QUALITY)
    private String quality;
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;
    @SerializedName(SERIALIZED_NAME_SEEDS)
    private Integer seeds;
    @SerializedName(SERIALIZED_NAME_PEERS)
    private Integer peers;
    @SerializedName(SERIALIZED_NAME_SIZE)
    private String size;
    @SerializedName(SERIALIZED_NAME_SIZE_BYTES)
    private Long sizeBytes;
    @SerializedName(SERIALIZED_NAME_DATE_UPLOADED)
    private String dateUploaded;
    @SerializedName(SERIALIZED_NAME_DATE_UPLOADED_UNIX)
    private Integer dateUploadedUnix;

    @SuppressWarnings("unused")
    public YtsTorrentInfo url(String url) {

        this.url = url;
        return this;
    }

    /**
     * Torrent file download link
     *
     * @return url
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent file download link")

    public String getUrl() {
        return url;
    }

    @SuppressWarnings("unused")
    public void setUrl(String url) {
        this.url = url;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo hash(String hash) {

        this.hash = hash;
        return this;
    }

    /**
     * Torrent hash
     *
     * @return hash
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent hash")

    public String getHash() {
        return hash;
    }

    @SuppressWarnings("unused")
    public void setHash(String hash) {
        this.hash = hash;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo quality(String quality) {

        this.quality = quality;
        return this;
    }

    /**
     * Torrent quality
     *
     * @return quality
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent quality")

    public String getQuality() {
        return quality;
    }

    @SuppressWarnings("unused")
    public void setQuality(String quality) {
        this.quality = quality;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Torrent recording type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent recording type")

    public String getType() {
        return type;
    }

    @SuppressWarnings("unused")
    public void setType(String type) {
        this.type = type;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo seeds(Integer seeds) {

        this.seeds = seeds;
        return this;
    }

    /**
     * Number of seeders
     *
     * @return seeds
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Number of seeders")

    public Integer getSeeds() {
        return seeds;
    }

    @SuppressWarnings("unused")
    public void setSeeds(Integer seeds) {
        this.seeds = seeds;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo peers(Integer peers) {

        this.peers = peers;
        return this;
    }

    /**
     * Number of peers
     *
     * @return peers
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Number of peers")

    public Integer getPeers() {
        return peers;
    }

    @SuppressWarnings("unused")
    public void setPeers(Integer peers) {
        this.peers = peers;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo size(String size) {

        this.size = size;
        return this;
    }

    /**
     * Torrent size
     *
     * @return size
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent size")

    public String getSize() {
        return size;
    }

    @SuppressWarnings("unused")
    public void setSize(String size) {
        this.size = size;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo sizeBytes(Long sizeBytes) {

        this.sizeBytes = sizeBytes;
        return this;
    }

    /**
     * Torrent size (bytes)
     *
     * @return sizeBytes
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Torrent size (bytes)")

    public Long getSizeBytes() {
        return sizeBytes;
    }

    @SuppressWarnings("unused")
    public void setSizeBytes(Long sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo dateUploaded(String dateUploaded) {

        this.dateUploaded = dateUploaded;
        return this;
    }

    /**
     * Date uploaded
     *
     * @return dateUploaded
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Date uploaded")

    public String getDateUploaded() {
        return dateUploaded;
    }

    @SuppressWarnings("unused")
    public void setDateUploaded(String dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

    @SuppressWarnings("unused")
    public YtsTorrentInfo dateUploadedUnix(Integer dateUploadedUnix) {

        this.dateUploadedUnix = dateUploadedUnix;
        return this;
    }

    /**
     * Date uploaded (unix format)
     *
     * @return dateUploadedUnix
     **/
    @SuppressWarnings("unused")
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Date uploaded (unix format)")

    public Integer getDateUploadedUnix() {
        return dateUploadedUnix;
    }

    @SuppressWarnings("unused")
    public void setDateUploadedUnix(Integer dateUploadedUnix) {
        this.dateUploadedUnix = dateUploadedUnix;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        YtsTorrentInfo ytsTorrentInfo = (YtsTorrentInfo) o;
        return Objects.equals(this.url, ytsTorrentInfo.url) &&
                Objects.equals(this.hash, ytsTorrentInfo.hash) &&
                Objects.equals(this.quality, ytsTorrentInfo.quality) &&
                Objects.equals(this.type, ytsTorrentInfo.type) &&
                Objects.equals(this.seeds, ytsTorrentInfo.seeds) &&
                Objects.equals(this.peers, ytsTorrentInfo.peers) &&
                Objects.equals(this.size, ytsTorrentInfo.size) &&
                Objects.equals(this.sizeBytes, ytsTorrentInfo.sizeBytes) &&
                Objects.equals(this.dateUploaded, ytsTorrentInfo.dateUploaded) &&
                Objects.equals(this.dateUploadedUnix, ytsTorrentInfo.dateUploadedUnix);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url, hash, quality, type, seeds, peers, size, sizeBytes,
                dateUploaded, dateUploadedUnix);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class YtsTorrentInfo {\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
        sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    seeds: ").append(toIndentedString(seeds)).append("\n");
        sb.append("    peers: ").append(toIndentedString(peers)).append("\n");
        sb.append("    size: ").append(toIndentedString(size)).append("\n");
        sb.append("    sizeBytes: ")
                .append(toIndentedString(sizeBytes))
                .append("\n");
        sb.append("    dateUploaded: ")
                .append(toIndentedString(dateUploaded))
                .append("\n");
        sb.append("    dateUploadedUnix: ")
                .append(toIndentedString(dateUploadedUnix))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
